config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "case#index"
  get "calendar", to: "calendar#global", as: :global_calendar
  get "timer", to: "time_recording#global", as: :global_timers

  scope "/profile" do
    get "edit", to: "profile#edit", as: :edit_profile
    post "edit", to: "profile#update", as: :update_profile

    get "writing-types", to: "profile#writing_types", as: :edit_writing_types

    get "writing-types/:writing_type_id", to: "profile#edit_writing_type", as: :edit_writing_type
    post "writing-types/:writing_type_id", to: "profile#update_writing_type", as: :update_writing_type
  end

  scope "/cases" do
    root to: "case#search", as: :cases
    get "new", to: "case#new", as: :new_case
    put "new", to: "case#create", as: :create_case
  end

  scope "/c/:case_id" do
    root to: "case#show", as: :show_case
    get "edit", to: "case#edit", as: :edit_case
    post "edit", to: "case#update", as: :update_case

    post "canonize", to: "case#canonize", as: :canonize_case

    get "pin", to: "case#pin", as: :pin_case
    get "unpin", to: "case#unpin", as: :unpin_case

    scope "/permissions" do
      root to: "permissions#index", as: :permissions

      get "new", to: "permissions#new", as: :new_permission
      post "new", to: "permissions#create", as: :create_permission

      get ":permission_id/edit", to: "permissions#edit", as: :edit_permission
      post ":permission_id/edit", to: "permissions#update", as: :update_permission

      get ":permission_id/delete", to: "permissions#delete", as: :delete_permission
      post ":permission_id/delete", to: "permissions#destroy", as: :destroy_permission
    end

    scope "/participants" do
      root to: "participants#index", as: :participants
      get "new", to: "participants#new", as: :new_participant
      post "new", to: "participants#create", as: :create_participant
      get ":participant_id/edit", to: "participants#edit", as: :edit_participant
      post ":participant_id/edit", to: "participants#update", as: :update_participant
      get ":participant_id/delete", to: "participants#delete", as: :delete_participant
      post ":participant_id/delete", to: "participants#destroy", as: :destroy_participant
    end

    scope "/represent" do
      get "new", to: "representments#new", as: :new_representment
      post "new", to: "representments#create", as: :create_representment
      get "new/:days/days", to: "representments#create_for_days", as: :create_representment_for_days
      get "clear", to: "representments#clear", as: :clear_representment
      get "step", to: "representments#step", as: :step
      get "clear-and-step", to: "representments#clear_and_step", as: :clear_and_step
    end

    scope "/notes" do
      root to: "notes#index", as: :notes
      get "new", to: "notes#new", as: :new_note
      post "new", to: "notes#create", as: :create_note
      get ":note_id/edit", to: "notes#edit", as: :edit_note
      post ":note_id/edit", to: "notes#update", as: :update_note
      get ":note_id/delete", to: "notes#delete", as: :delete_note
      post ":note_id/delete", to: "notes#destroy", as: :destroy_note
    end

    scope "/calendar" do
      root to: "calendar#index", as: :calendar
      get "new", to: "calendar#new", as: :new_event
      post "new", to: "calendar#create", as: :create_event
      get ":event_id/edit", to: "calendar#edit", as: :edit_event
      post ":event_id/edit", to: "calendar#update", as: :update_event
      get ":event_id/delete", to: "calendar#delete", as: :delete_event
      post ":event_id/delete", to: "calendar#destroy", as: :destroy_event
    end

    scope "/documents" do
      root to: "documents#index", as: :documents

      get "fo-:folder_id", to: "documents#folder", as: :folder
      get "fo/new", to: "documents#new_folder", as: :new_folder
      post "fo/new", to: "documents#create_folder", as: :create_folder
      get "fo-:folder_id/edit", to: "documents#edit_folder", as: :edit_folder
      post "fo-:folder_id/edit", to: "documents#update_folder", as: :update_folder

      get "fo-:folder_id/do-:document_id", to: "documents#document", as: :document
      get "fo-:folder_id/do/new", to: "documents#new_document", as: :new_document
      post "fo-:folder_id/do/new", to: "documents#create_document", as: :create_document
      get "fo-:folder_id/do-:document_id/edit", to: "documents#edit_document", as: :edit_document
      post "fo-:folder_id/do-:document_id/edit", to: "documents#update_document", as: :update_document

      get "fo-:folder_id/do-:document_id/i/new", to: "documents#new_document_item", as: :new_document_item
      post "fo-:folder_id/do-:document_id/i/new", to: "documents#create_document_item", as: :create_document_item
    end

    scope "/tasks" do
      root to: "tasks#index", as: :tasks

      get ":task_id/edit", to: "tasks#edit", as: :edit_task
      post ":task_id/edit", to: "tasks#update", as: :update_task
      get "new", to: "tasks#new", as: :new_task
      post "new", to: "tasks#create", as: :create_task
      get ":task_id/delete", to: "tasks#delete", as: :delete_task
      post ":task_id/delete", to: "tasks#destroy", as: :destroy_task

      get "column/:task_column_id/edit", to: "tasks#edit_task_column", as: :edit_task_column
      post "column/:task_column_id/edit", to: "tasks#update_task_column", as: :update_task_column
      get "column/new", to: "tasks#new_task_column", as: :new_task_column
      post "column/new", to: "tasks#create_task_column", as: :create_task_column
    end

    scope "/writing" do
      root to: "writing#index", as: :writings
      get ":type_id/new", to: "writing#new", as: :new_writing
      post ":type_id/new", to: "writing#create", as: :create_writing

      get "draft/:draft_id/edit", to: "writing#edit", as: :edit_writing
      post "draft/:draft_id/edit", to: "writing#update", as: :update_writing

      get "draft/:draft_id/finalize", to: "writing#finalize", as: :finalize_writing
      get "draft/:draft_id/download", to: "writing#download", as: :download_writing
    end

    scope "/timer" do
      root to: "time_recording#index", as: :timers

      get "start", to: "time_recording#start", as: :start_timer
      get "stop", to: "time_recording#stop", as: :stop_timer

      get "new", to: "time_recording#new", as: :new_timer
      post "new", to: "time_recording#create", as: :create_timer

      get ":time_record_id/edit", to: "time_recording#edit", as: :edit_timer
      post ":time_record_id/edit", to: "time_recording#update", as: :update_timer

      get ":time_record_id/delete", to: "time_recording#delete", as: :delete_timer
      post ":time_record_id/delete", to: "time_recording#destroy", as: :destroy_timer
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :case
  belongs_to :task_column
  belongs_to :task_resolution_type, optional: true

  has_rich_text :description

  default_scope { where.not(is_deleted: true) }

  scope :that_are_open, -> { where(is_resolved: false) }
  scope :that_are_overdue, -> { where("due < ?", Date.today) }

  def status
    return :deleted if is_deleted
    return :resolved if is_resolved
    return :overdue if due != nil && due < Date.today
    :pending
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_case, only: [ :index, :edit, :update, :new, :create, :edit_task_column,
                                   :update_task_column, :new_task_column, :create_task_column,
                                  :delete, :destroy ]
  before_action :get_task, only: [ :edit, :update, :delete, :destroy ]
  before_action :get_task_column, only: [ :edit_task_column, :update_task_column ]

  def index
    return if require_permission! :tasks_read
    render layout: "layouts/case_view"
  end

  def edit
    return if require_permission! :tasks_read
    render layout: "layouts/case_view"
  end

  def update
    return if require_permission! :tasks_write
    @task.update!(
      title: params[:task][:title],
      description: params[:task][:description],
      user: params[:task][:user].blank? ? nil : User.find(params[:task][:user]),
      task_column: @case.task_columns.find(params[:task][:task_column]),
      due: params[:task][:due].blank? ? nil : params[:task][:due].to_date,
      is_resolved: params[:task][:is_resolved] == "1",
      task_resolution_type: (params[:task][:task_resolution_type].blank? ? nil :
          TaskResolutionType.find(params[:task][:task_resolution_type]))
    )
    @case.touch

    flash[:success] = "Aufgabe erfolgreich gespeichert."
    render "tasks/edit", layout: "layouts/case_view"
  end

  def new
    return if require_permission! :tasks_write
    @task = Task.new(
      case: @case,
      task_column: @case.task_columns.where(default_token: "open").first,
      is_resolved: false,
      is_deleted: false
    )

    render layout: "layouts/case_view"
  end

  def create
    return if require_permission! :tasks_write
    @task = Task.create!(
      case: @case,
      is_deleted: false,
      title: params[:task][:title],
      description: params[:task][:description],
      user: params[:task][:user].blank? ? nil : User.find(params[:task][:user]),
      task_column: @case.task_columns.find(params[:task][:task_column]),
      due: params[:task][:due].blank? ? nil : params[:task][:due].to_date,
      is_resolved: params[:task][:is_resolved] == "1",
      task_resolution_type: (params[:task][:task_resolution_type].blank? ? nil :
          TaskResolutionType.find(params[:task][:task_resolution_type]))
    )

    flash[:success] = "Aufgabe erfolgreich erstellt."
    redirect_to edit_task_path(@case, @task)
  end

  def edit_task_column
    return if require_permission! :tasks_write
    render layout: "layouts/case_view"
  end

  def update_task_column
    return if require_permission! :tasks_write
    @task_column.update!(
      title: params[:task_column][:title],
      is_enabled: params[:task_column][:is_enabled] == "1"
    )
    @case.touch

    flash[:success] = "Spalte erfolgreich gespeichert."
    render "tasks/edit_task_column", layout: "layouts/case_view"
  end

  def new_task_column
    return if require_permission! :tasks_write
    @task_column = TaskColumn.new(
      case: @case,
      is_enabled: true,
      default_token: ""
    )

    render layout: "layouts/case_view"
  end

  def create_task_column
    return if require_permission! :tasks_write
    @task_column = TaskColumn.create!(
      case: @case,
      title: params[:task_column][:title],
      is_enabled: params[:task_column][:is_enabled] == "1",
      default_token: ""
    )
    @case.touch

    flash[:success] = "Spalte erfolgreich erstellt."
    redirect_to edit_task_column_path(@case, @task_column)
  end

  def delete
    return if require_permission! :tasks_write
    render layout: "layouts/case_view"
  end

  def destroy
    return if require_permission! :tasks_write
    @task.update!(is_deleted: true)
    @case.touch
    flash[:success] = "Aufgabe erfolgreich gelöscht."
    redirect_to tasks_path(@case)
  end

  protected

  def get_task
    @task = Task.where(case: @case).find(params[:task_id])
  end

  def get_task_column
    @task_column = TaskColumn.where(case: @case).find(params[:task_column_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with url: form_to, model: task, method: :post do |form| %>
  <div class="row">
    <div class="col col-md-8">
      <div class="mb-3">
        <%= form.text_field :title, class: 'form-control h3', placeholder: 'Betreff eingeben...', readonly: !@case.user_has_permission?(current_user, :tasks_write) %>
      </div>

      <div class="mb-3">
        <% if @case.user_has_permission?(current_user, :tasks_write) %>
          <%= form.rich_text_area :description, placeholder: 'Schreiben Sie einfach los...' %>
        <% else %>
          <div class="rounded">
            <%= task.description %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col col-md-4">
      <div class="form-floating mb-3">
        <%= form.select :user, User.all.map { |u| [u.display_name, u.id]}, {selected: task.user&.id, include_blank: 'Ggf. auswählen...'}, { class: 'form-select', disabled: !@case.user_has_permission?(current_user, :tasks_write) } %>
        <%= form.label :user, 'Zugewiesen an' %>
      </div>
      
      <div class="form-floating mb-3">
        <%= form.select :task_column, @case.task_columns.all.map { |dt| [dt.title, dt.id]}, {selected: task.task_column&.id, prompt: 'Bitte auswählen...'}, { class: 'form-select', disabled: !@case.user_has_permission?(current_user, :tasks_write) } %>
        <%= form.label :task_column, 'Status' %>
      </div>

      <div class="form-floating mb-3">
        <%= form.date_field :due, class: 'form-control', placeholder: '', readonly: !@case.user_has_permission?(current_user, :tasks_write) %>
        <%= form.label :due, 'Fällig am' %>
      </div>

      <div class="card mb-3">
        <div class="card-header py-1 px-2">
          <div class="form-check m-0">
            <%= form.check_box :is_resolved, class: 'form-check-input', checked: task.is_resolved, disabled: !@case.user_has_permission?(current_user, :tasks_write) %>
            <%= form.label :is_resolved, 'Aufgabe als erledigt markieren' %>
          </div>
        </div>
        <div class="card-body p-1">
          <%= form.select :task_resolution_type, TaskResolutionType.order(:title).all.map { |dt| [dt.title, dt.id]}, {selected: task.task_resolution_type&.id, include_blank: 'Ggf. auswählen...'}, { class: 'form-select', disabled: !@case.user_has_permission?(current_user, :tasks_write) } %>
        </div>
      </div>
    </div>
  </div>


  <% if @case.user_has_permission?(current_user, :tasks_write) %>
    <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
    <%= link_to 'Abbrechen', tasks_url(@case), class: 'btn btn-secondary mb-3' %>
    <% unless task.new_record? %>
      <%= link_to 'Aufgabe löschen', delete_task_url(@case, task), class: 'btn btn-outline-danger mb-3' %>
    <% end %>
  <% else %>
    <%= link_to 'Zurück zur Übersicht', tasks_url(@case), class: 'btn btn-secondary mb-3' %>
  <% end %>
<% end %>

app/views/tasks/_task_column_form.html.erb
<%= form_with url: form_to, model: task_column, method: :post do |form| %>
  <div class="form-floating mb-3">
    <%= form.text_field :title, class: 'form-control', placeholder: '' %>
    <%= form.label :title, 'Titel' %>
  </div>

  <div class="form-check mb-3">
    <%= form.check_box :is_enabled, class: 'form-check-input', checked: task_column.is_enabled %>
    <%= form.label :is_enabled, 'Spalte ist aktiviert' %>
  </div>

  <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
  <%= link_to 'Abbrechen', tasks_url(@case), class: 'btn btn-secondary mb-3' %>
<% end %>

app/views/tasks/delete.html.erb
<%= render 'case/case_header', view: :tasks %>
<h2 class="h5 mt-3 mb-3 fw-bold">Aufgabe löschen</h2>

<p>Wollen Sie die folgende Aufgabe wirklich löschen?</p>
<p class="fw-bold"><%= @task.title %></p>

<%= form_with url: destroy_task_path(@case, @task), model: @task, method: :post do |form| %>
<%= form.submit 'Aufgabe jetzt löschen', class: 'btn btn-danger mb-3' %>
<%= link_to 'Abbrechen', edit_note_path(@case, @task), class: 'btn btn-secondary mb-3' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'case/case_header', view: :tasks %>
<%= render 'tasks/form', form_to: update_task_path(@case, @task), task: @task %>

app/views/tasks/edit_task_column.html.erb
<%= render 'case/case_header', view: :tasks %>
<%= render 'tasks/task_column_form', form_to: update_task_column_path(@case, @task_column), task_column: @task_column %>

app/views/tasks/index.html.erb
<%= render 'case/case_header', view: :tasks %>


<% if @case.user_has_permission?(current_user, :tasks_write) %>
  <div class="clearfix mb-3">
    <div class="float-end">
      <a href="<%= new_task_column_url(@case) %>" class="btn btn-outline-dark">Neue Spalte</a>
      <a href="<%= new_task_url(@case) %>" class="btn btn-dark">Neue Aufgabe</a>
    </div>
  </div>
<% end %>

<div class="row flex-nowrap g-2 overflow-auto pb-3">
  <% @case.task_columns.order(:title).each do |col| %>
    <div class="col col-4">
      <div class="card text-bg-light">
        <div class="card-header pe-2 fw-bold">
          <% if @case.user_has_permission?(current_user, :tasks_write) %>
            <a href="<%= edit_task_column_url(@case, col) %>" class="btn btn-sm btn-outline-dark float-end">Bearbeiten</a>
          <% end %>
          <h2 class="h5 mb-1 mt-1 fw-bold"><%= col.title %></h2>
          <p class="mb-0 fs-small fw-normal text-secondary">
            <% if col.tasks.that_are_overdue.count > 0 %>
            <%= col.tasks.that_are_open.count %> offene Aufgabe(n) &middot;
            davon <%= col.tasks.that_are_overdue.count %> überfällig
            <% else %>
            <%= col.tasks.that_are_open.count %> offene Aufgabe(n)
            <% end %>
          </p>
        </div>
        <div class="card-body p-2 pb-0">
          <% if col.tasks.any? %>
            <% col.tasks.order(:is_resolved, :due, :updated_at).each do |task|%>
              <a href="<%= edit_task_url(@case, task) %>" class="card mb-2 text-decoration-none <%= task.status == :overdue ? "bg-warning-subtle" : "" %> <%= task.status == :resolved ? "border-success opacity-25" : "shadow-sm" %>">
                <div class="card-body py-2">
                  <p class="mb-0"><strong><%= task.title %></strong></p>
                  <% if task.user == current_user %>
                    <p class="mb-0 fs-small">Für: <strong class="text-bg-warning"><%= task.user.display_name %></strong></p>
                  <% elsif task.user %>
                    <p class="mb-0 fs-small">Für: <%= task.user.display_name %></p>
                  <% else %>
                    <p class="mb-0 fs-small">nicht zugewiesen</p>
                  <% end %>
                  <% if task.due %>
                    <p class="mb-0 fs-small">Fällig: <%= task.due.strftime("%d.%m.%Y") %></p>
                  <% end %>
                </div>
              </a>
            <% end %>
          <% else %>
            <div class="mb-2 p-2 text-center fs-small">Hier ist gerade nichts.</div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= render 'case/case_header', view: :tasks %>
<%= render 'tasks/form', form_to: create_task_path(@case, @task), task: @task %>

app/views/tasks/new_task_column.html.erb
<%= render 'case/case_header', view: :tasks %>
<%= render 'tasks/task_column_form', form_to: create_task_column_path(@case), task_column: @task_column %>