config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "case#index"
  get "calendar", to: "calendar#global", as: :global_calendar
  get "timer", to: "time_recording#global", as: :global_timers

  scope "/profile" do
    get "edit", to: "profile#edit", as: :edit_profile
    post "edit", to: "profile#update", as: :update_profile

    get "writing-types", to: "profile#writing_types", as: :edit_writing_types

    get "writing-types/:writing_type_id", to: "profile#edit_writing_type", as: :edit_writing_type
    post "writing-types/:writing_type_id", to: "profile#update_writing_type", as: :update_writing_type
  end

  scope "/cases" do
    root to: "case#search", as: :cases
    get "new", to: "case#new", as: :new_case
    put "new", to: "case#create", as: :create_case
  end

  scope "/c/:case_id" do
    root to: "case#show", as: :show_case
    get "edit", to: "case#edit", as: :edit_case
    post "edit", to: "case#update", as: :update_case

    post "canonize", to: "case#canonize", as: :canonize_case

    get "pin", to: "case#pin", as: :pin_case
    get "unpin", to: "case#unpin", as: :unpin_case

    scope "/permissions" do
      root to: "permissions#index", as: :permissions

      get "new", to: "permissions#new", as: :new_permission
      post "new", to: "permissions#create", as: :create_permission

      get ":permission_id/edit", to: "permissions#edit", as: :edit_permission
      post ":permission_id/edit", to: "permissions#update", as: :update_permission

      get ":permission_id/delete", to: "permissions#delete", as: :delete_permission
      post ":permission_id/delete", to: "permissions#destroy", as: :destroy_permission
    end

    scope "/participants" do
      root to: "participants#index", as: :participants
      get "new", to: "participants#new", as: :new_participant
      post "new", to: "participants#create", as: :create_participant
      get ":participant_id/edit", to: "participants#edit", as: :edit_participant
      post ":participant_id/edit", to: "participants#update", as: :update_participant
      get ":participant_id/delete", to: "participants#delete", as: :delete_participant
      post ":participant_id/delete", to: "participants#destroy", as: :destroy_participant
    end

    scope "/represent" do
      get "new", to: "representments#new", as: :new_representment
      post "new", to: "representments#create", as: :create_representment
      get "new/:days/days", to: "representments#create_for_days", as: :create_representment_for_days
      get "clear", to: "representments#clear", as: :clear_representment
      get "step", to: "representments#step", as: :step
      get "clear-and-step", to: "representments#clear_and_step", as: :clear_and_step
    end

    scope "/notes" do
      root to: "notes#index", as: :notes
      get "new", to: "notes#new", as: :new_note
      post "new", to: "notes#create", as: :create_note
      get ":note_id/edit", to: "notes#edit", as: :edit_note
      post ":note_id/edit", to: "notes#update", as: :update_note
      get ":note_id/delete", to: "notes#delete", as: :delete_note
      post ":note_id/delete", to: "notes#destroy", as: :destroy_note
    end

    scope "/calendar" do
      root to: "calendar#index", as: :calendar
      get "new", to: "calendar#new", as: :new_event
      post "new", to: "calendar#create", as: :create_event
      get ":event_id/edit", to: "calendar#edit", as: :edit_event
      post ":event_id/edit", to: "calendar#update", as: :update_event
      get ":event_id/delete", to: "calendar#delete", as: :delete_event
      post ":event_id/delete", to: "calendar#destroy", as: :destroy_event
    end

    scope "/documents" do
      root to: "documents#index", as: :documents

      get "fo-:folder_id", to: "documents#folder", as: :folder
      get "fo/new", to: "documents#new_folder", as: :new_folder
      post "fo/new", to: "documents#create_folder", as: :create_folder
      get "fo-:folder_id/edit", to: "documents#edit_folder", as: :edit_folder
      post "fo-:folder_id/edit", to: "documents#update_folder", as: :update_folder

      get "fo-:folder_id/do-:document_id", to: "documents#document", as: :document
      get "fo-:folder_id/do/new", to: "documents#new_document", as: :new_document
      post "fo-:folder_id/do/new", to: "documents#create_document", as: :create_document
      get "fo-:folder_id/do-:document_id/edit", to: "documents#edit_document", as: :edit_document
      post "fo-:folder_id/do-:document_id/edit", to: "documents#update_document", as: :update_document

      get "fo-:folder_id/do-:document_id/i/new", to: "documents#new_document_item", as: :new_document_item
      post "fo-:folder_id/do-:document_id/i/new", to: "documents#create_document_item", as: :create_document_item
    end

    scope "/tasks" do
      root to: "tasks#index", as: :tasks

      get ":task_id/edit", to: "tasks#edit", as: :edit_task
      post ":task_id/edit", to: "tasks#update", as: :update_task
      get "new", to: "tasks#new", as: :new_task
      post "new", to: "tasks#create", as: :create_task
      get ":task_id/delete", to: "tasks#delete", as: :delete_task
      post ":task_id/delete", to: "tasks#destroy", as: :destroy_task

      get "column/:task_column_id/edit", to: "tasks#edit_task_column", as: :edit_task_column
      post "column/:task_column_id/edit", to: "tasks#update_task_column", as: :update_task_column
      get "column/new", to: "tasks#new_task_column", as: :new_task_column
      post "column/new", to: "tasks#create_task_column", as: :create_task_column
    end

    scope "/writing" do
      root to: "writing#index", as: :writings
      get ":type_id/new", to: "writing#new", as: :new_writing
      post ":type_id/new", to: "writing#create", as: :create_writing

      get "draft/:draft_id/edit", to: "writing#edit", as: :edit_writing
      post "draft/:draft_id/edit", to: "writing#update", as: :update_writing

      get "draft/:draft_id/finalize", to: "writing#finalize", as: :finalize_writing
      get "draft/:draft_id/download", to: "writing#download", as: :download_writing
    end

    scope "/timer" do
      root to: "time_recording#index", as: :timers

      get "start", to: "time_recording#start", as: :start_timer
      get "stop", to: "time_recording#stop", as: :stop_timer

      get "new", to: "time_recording#new", as: :new_timer
      post "new", to: "time_recording#create", as: :create_timer

      get ":time_record_id/edit", to: "time_recording#edit", as: :edit_timer
      post ":time_record_id/edit", to: "time_recording#update", as: :update_timer

      get ":time_record_id/delete", to: "time_recording#delete", as: :delete_timer
      post ":time_record_id/delete", to: "time_recording#destroy", as: :destroy_timer
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :case
  belongs_to :folder
  belongs_to :document_type
  belongs_to :user, optional: true
  belongs_to :participant, optional: true
  belongs_to :note, optional: true

  has_many :document_items

  def author_name
    return user.display_name unless user.blank?
    participant.name
  end

  def true_number
    folder.documents.count - folder.documents.where("created_at > ?", created_at).count
  end

  def document_number
    (folder.documents.count > 667 ? "%04d" : "%03d") % true_number
  end

  def printable_name
    document_number + "_" + name.gsub(/[^a-zA-Z0-9-ÄäÖöÜüß]+/, "_")
  end

  def primary_item
    document_items.where(is_primary: true).first
  end
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :get_case, only: [ :index, :folder, :edit_folder, :update_folder, :new_folder,
                                   :create_folder, :document, :new_document_item,
                                   :create_document_item, :edit_document, :update_document,
                                   :new_document, :create_document ]
  before_action :get_folder, only: [ :folder, :edit_folder, :update_folder, :document,
                                     :new_document_item, :create_document_item, :edit_document,
                                     :update_document, :new_document, :create_document ]
  before_action :get_document, only: [ :document, :new_document_item, :create_document_item,
                                       :edit_document, :update_document ]

  def index
    return if require_permission! :documents_read
    redirect_to folder_url(@case, @case.default_folder)
  end

  def folder
    return if require_permission! :documents_read
    render layout: "layouts/case_view"
  end

  def edit_folder
    return if require_permission! :documents_write
    render layout: "layouts/case_view"
  end

  def update_folder
    return if require_permission! :documents_write
    @folder.update!(name: params[:folder][:name])
    @case.touch

    flash[:success] = "Ordner erfolgreich gespeichert."
    redirect_to folder_path(@case, @folder)
  end

  def new_folder
    return if require_permission! :documents_write
    @folder = Folder.new(
      case: @case,
      is_default: false,
      is_protected: false,
      password: nil
    )
    render layout: "layouts/case_view"
  end

  def create_folder
    return if require_permission! :documents_write
    @folder = Folder.create!(
      case: @case,
      name: params[:folder][:name],
      is_default: false,
      is_protected: false,
      password: nil
    )
    @case.touch

    flash[:success] = "Ordner erfolgreich angelegt."
    redirect_to folder_path(@case, @folder)
  end

  def document
    return if require_permission! :documents_read
    render layout: "layouts/case_view"
  end

  def edit_document
    return if require_permission! :documents_write
    render layout: "layouts/case_view"
  end

  def update_document
    return if require_permission! :documents_write
    has_user = !params[:document][:user].blank?

    @document.update!(
      name: params[:document][:name],
      sent_at: params[:document][:sent_at].to_date,
      document_type: DocumentType.find(params[:document][:document_type]),
      participant: has_user ? nil : @case.participants.find(params[:document][:participant]),
      user: has_user ? User.find(params[:document][:user]) : nil
    )

    if @document.primary_item.blank? and params[:document][:file]
      uploaded_file = params[:document][:file]
      @document_item = DocumentItem.create!(
        case: @case,
        folder: @folder,
        document: @document,
        file_name: uploaded_file.original_filename,
        is_primary: true,
        is_attachment: false,
        is_transactional: false
      )
      @document_item.file.attach(uploaded_file)
    end

    @case.touch

    flash[:success] = "Dokument erfolgreich bearbeitet."
    redirect_to document_path(@case, @folder, @document)
  end

  def new_document
    return if require_permission! :documents_write
    @document = Document.new(
      case: @case,
      folder: @folder,
      sent_at: Date.today,
      is_deleted: false
    )

    render layout: "layouts/case_view"
  end

  def create_document
    return if require_permission! :documents_write
    has_user = !params[:document][:user].blank?

    @document = Document.create!(
      case: @case,
      folder: @folder,
      is_deleted: false,
      name: params[:document][:name],
      sent_at: params[:document][:sent_at].to_date,
      document_type: DocumentType.find(params[:document][:document_type]),
      participant: has_user ? nil : @case.participants.find(params[:document][:participant]),
      user: has_user ? User.find(params[:document][:user]) : nil
    )

    if @document.primary_item.blank? and params[:document][:file]
      uploaded_file = params[:document][:file]
      @document_item = DocumentItem.create!(
        case: @case,
        folder: @folder,
        document: @document,
        file_name: uploaded_file.original_filename,
        is_primary: true,
        is_attachment: false,
        is_transactional: false
      )
      @document_item.file.attach(uploaded_file)
    end

    @case.touch

    flash[:success] = "Dokument erfolgreich erstellt."
    redirect_to document_path(@case, @folder, @document)
  end

  def new_document_item
    return if require_permission! :documents_write
    @document_item = DocumentItem.new(
      case: @case,
      folder: @folder,
      document: @document
    )

    render layout: "layouts/case_view"
  end

  def create_document_item
    return if require_permission! :documents_write
    uploaded_file = params[:document_item][:file]
    @document_item = DocumentItem.create!(
      case: @case,
      folder: @folder,
      document: @document,
      file_name: uploaded_file.original_filename,
      is_primary: params[:document_item][:type].to_sym == :primary,
      is_attachment: params[:document_item][:type].to_sym == :attachment,
      is_transactional: params[:document_item][:type].to_sym == :transactional
    )
    @document_item.file.attach(uploaded_file)
    @case.touch

    flash[:success] = "Datei erfolgreich hochgeladen."
    redirect_to document_path(@case, @folder, @document)
  end

  protected

  def get_folder
    @folder = Folder.where(case: @case).find(params[:folder_id])
  end

  def get_document
    @document = Document.where(case: @case, folder: @folder).find(params[:document_id])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document_form.html.erb
<%= form_with url: form_to, model: document, method: :post do |form| %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: '' %>
    <%= form.label :name, 'Name des Dokuments' %>
  </div>

  <div class="form-floating mb-3">
    <%= form.date_field :sent_at, class: 'form-control', placeholder: '' %>
    <%= form.label :sent_at, 'Datum des Dokuments' %>
  </div>

  <div class="form-floating mb-3">
    <%= form.select :document_type, DocumentType.all.map { |dt| [dt.title, dt.id]}, {selected: document.document_type&.id, prompt: 'Bitte auswählen...'}, { class: 'form-select' } %>
    <%= form.label :document_type, 'Dokumententyp' %>
  </div>

  <p class="mt-3 mb-1">Wählen Sie aus, von wem das Dokument stammt. Sie können nur entweder eine/n Beteiligte/n oder eine/n Nutzer/in auswählen. Wenn Sie beide auswählen, geht die/der Nutzer/in vor.</p>

  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="form-floating">
        <%= form.select :participant, @case.participants.all.map { |u| [u.name, u.id]}, {selected: document.participant&.id, include_blank: 'Ggf. auswählen...'}, { class: 'form-select' } %>
        <%= form.label :participant, 'Beteiligter' %>
      </div>
    </div>
    <div class="col col-md-6">
      <div class="form-floating">
        <%= form.select :user, User.all.map { |u| [u.display_name, u.id]}, {selected: document.user&.id, include_blank: 'Ggf. auswählen...'}, { class: 'form-select' } %>
        <%= form.label :user, 'Nutzer/in' %>
      </div>
    </div>
  </div>

  <% if document.primary_item.blank? %>
  <p class="mt-3 mb-1">Sie können auch schon bereits eine Hauptdatei für dieses Dokument hochladen:</p>

  <div class="mb-3">
    <%= form.file_field :file, class: 'form-control', placeholder: '' %>
  </div>

  <% end %>

  <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
  <%= link_to 'Abbrechen', document.persisted? ? document_url(@case, @folder, document) : folder_url(@case, @folder), class: 'btn btn-secondary mb-3' %>
<% end %>

app/views/documents/_folder_form.html.erb
<%= form_with url: form_to, model: folder, method: :post do |form| %>
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: 'form-control', placeholder: '' %>
    <%= form.label :name, 'Ordnername' %>
  </div>

  <% if folder.is_default %>
  <p>Dieser Ordner ist der <strong>Standard-Ordner</strong>, der verwendet wird, wenn kein anderer Ordner ausgewählt wird.</p>
  <% end %>

  <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
  <%= link_to 'Abbrechen', folder_url(@case, (@folder.blank? ? @folder : @case.default_folder)), class: 'btn btn-secondary mb-3' %>
<% end %>

app/views/documents/_template.html.erb
<%= render 'case/case_header', view: :docs %>
<div class="row">
  <div class="col-12 col-md-4 d-print-none">
    <div class="list-group mb-3">
      <% @case.folders.order(is_default: :desc, name: :asc).each do |f| %>
        <a href="<%= folder_url(@case, f) %>" class="list-group-item list-group-item-action <%= 'active list-group-item-light' if folder&.id == f.id %>">
          <% if f.is_default %>
          <p class="mb-0">🏠 <%= f.name %></p>
          <% else %>
          <p class="mb-0">📁 <%= f.name %></p>
          <% end %>
        </a>
      <% end %>
      <a href="<%= writings_url(@case) %>" class="list-group-item list-group-item-action">Entwürfe</a>
      <% if @case.user_has_permission?(current_user, :documents_write) %>
        <a href="<%= new_folder_url(@case) %>" class="list-group-item list-group-item-action <%= 'active list-group-item-light' if folder&.new_record? %>">Neuer Ordner</a>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-md-8 d-print-fullwidth">
    <%= yield %>
  </div>
</div>

app/views/documents/document.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h5 mt-3 mb-1 fw-bold">
  <%= link_to @folder.printable_name, folder_url(@case, @folder), class: 'text-decoration-none' %>/<%= @document.printable_name %>/
  <% unless @document.primary_item.blank? %>
    <%= link_to "💾 #{@document.primary_item.short_file_name}", url_for(@document.primary_item.file),
              class: 'btn btn-outline-dark py-0 fw-bold shadow-sm my-1', target: '_blank' %>
  <% end %>
</h3>

<p class="mb-3 fs-small"><%= @document.document_type.title %> von <%= @document.author_name %>, <%= @document.sent_at.strftime("%d.%m.%Y") %></p>

<% if @document.document_items.any? %>

<% if @case.user_has_permission?(current_user, :documents_write) %>
  <a href="<%= new_document_item_path(@case, @folder, @document) %>" class="btn btn-secondary btn-sm mb-3">Weitere Datei hochladen</a>
  <a href="<%= edit_document_path(@case, @folder, @document) %>" class="btn btn-secondary btn-sm mb-3">Dokument bearbeiten</a>
<% end %>

<div class="list-group list-group-flush mb-3">
  <% @document.document_items.default_order.each do |item| %>
  <div class="list-group-item">
    <div class="row mb-1">
      <%= link_to url_for(item.file), class: 'col pt-0 d-block link-dark text-decoration-none', target: '_blank' do %>
        <% if !item.file.blank? %>
        <h4 class="h6 mb-1 fw-bold"><%= item.file_name %></h4>
        <p class="mb-0 fs-small"><%= item.file_type %>, <%= "%.2f" % (item.file.byte_size / 1.0.megabyte) %> MB</p>
        <% else %>
        <h4 class="h6 fw-bold text-danger m-0 mb-1"><%= item.file_name %></h4>
        <p class="mb-0 fs-small">Datei nicht gefunden</p>
        <% end %>
      <% end %>
      <div class="col-auto pt-0">
        <% case item.type %>
        <% when :primary %>
        <span class="badge text-bg-primary fs-5">Hauptdatei</span>
        <% when :attachment %>
        <span class="badge text-bg-secondary">Anlage</span>
        <% when :transactional %>
        <span class="badge text-bg-secondary">Beleg</span>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<h4 class="mt-5 mb-3 h5">Notizen zu diesem Dokument</h4>

<% if !@document.note.blank? %>

<div class="card mb-3">
  <div class="card-body">
    <%= @document.note.content %>
  </div>
  <div class="card-footer">
    <a href="<%= edit_note_url(@case, @document.note) %>" class="btn btn-outline-secondary btn-sm">Notiz bearbeiten</a>
  </div>
</div>



<% else %>
<p>Für dieses Dokument wurden noch keine Notiz erstellt. <a href="<%= new_note_url(@case, document: @document) %>">Jetzt erstellen</a></p>
<% end %>

<% else %>
<p>Für dieses Dokument wurden noch keine Dateien hochgeladen.</p>

<% if @case.user_has_permission?(current_user, :documents_write) %>
  <p>
    <a href="<%= new_document_item_path(@case, @folder, @document) %>" class="btn btn-primary">Jetzt Datei hochladen</a>
    <a href="<%= edit_document_path(@case, @folder, @document) %>" class="btn btn-secondary">Dokument bearbeiten</a>
  </p>
<% end %>

<% end %>
<% end %>

app/views/documents/edit_document.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h3 mb-3 fw-bold">Dokument bearbeiten</h3>

<%= render 'documents/document_form', document: @document, form_to: update_document_url(@case, @folder, @document) %>

<% end %>

app/views/documents/edit_folder.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h3 mb-3 fw-bold">Ordner bearbeiten</h3>

<%= render 'documents/folder_form', folder: @folder, form_to: update_folder_url(@case, @folder) %>

<% end %>

app/views/documents/folder.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h5 mt-3 mb-3 fw-bold"><%= @folder.printable_name %>/</h3>

<% if @case.user_has_permission?(current_user, :documents_write) %>
  <div class="mb-4">
    <a href="<%= new_document_url(@case, @folder) %>" class="btn btn-primary btn-sm">Dokument hinzufügen</a>
    <a href="<%= edit_folder_url(@case, @folder) %>" class="btn btn-secondary btn-sm">Ordner bearbeiten</a>
  </div>
<% end %>

<% if @folder.documents.any? %>
<div class="list-group list-group-flush mb-3">
  <% @folder.documents.order(created_at: :desc).each_with_index do |d, id| %>
  <div class="list-group-item">
    <div class="row mb-1">
      <div class="col-auto">
        <a href="<%= document_url(@case, @folder, d) %>" class="badge fs-5 fw-bold text-bg-dark text-decoration-none px-1"><%= (d.document_number) %></a>
      </div>
      <%= link_to document_url(@case, @folder, d), class: 'col pt-0 d-block link-dark text-decoration-none' do %>
        <h4 class="h6 fw-bold m-0 mb-1"><%= d.name %></h4>
        <p class="m-0 fs-small"><%= d.author_name %>, <%= d.sent_at.strftime("%d.%m.%Y") %></p>
      <% end %>
      <div class="col-auto pt-0">
        <% if d.primary_item.blank? %>
          <span class="badge text-secondary border"><%= d.document_type.title %></span>
        <% else %>
          <%= link_to "#{d.document_type.title}", url_for(d.primary_item.file),
                      class: 'badge text-bg-secondary text-decoration-none', target: '_blank' %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% else %>
<p>Dieser Ordner ist leer.</p>
<% end %>

<% end %>

app/views/documents/new_document.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h3 mb-3 fw-bold">Dokument erstellen</h3>

<%= render 'documents/document_form', document: @document, form_to: create_document_url(@case, @folder) %>

<% end %>

app/views/documents/new_document_item.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h5 mt-3 mb-3 fw-bold">
  <%= link_to @folder.printable_name, folder_url(@case, @folder), class: 'text-decoration-none' %>/<%= @document.printable_name %>/
</h3>

<%= form_with url: create_document_item_url, model: @document_item, method: :post do |form| %>
  <div class="mb-3">
    <%= form.file_field :file, class: 'form-control', placeholder: '' %>
  </div>

  <p class="mb-3">Welche Rolle spielt die Datei für dieses Dokument?</p>

  <div class="mb-3">
    <div class="form-check mb-1">
      <%= form.radio_button :type, :primary, class: 'form-check-input', checked: @document.document_items.count == 0 %>
      <%= form.label :type_primary, 'Hauptdatei' %>
    </div>

    <div class="form-check mb-1">
      <%= form.radio_button :type, :attachment, class: 'form-check-input' %>
      <%= form.label :type_attachment, 'Anlage' %>
    </div>

    <div class="form-check mb-1">
      <%= form.radio_button :type, :transactional, class: 'form-check-input' %>
      <%= form.label :type_transactional, 'Transaktionsbeleg (z. B. E-Mail-Lesebestätigung oder ERV-Beleg)' %>
    </div>

    <div class="form-check mb-1">
      <%= form.radio_button :type, :other, class: 'form-check-input', checked: @document.document_items.count != 0 %>
      <%= form.label :type_other, 'Sonstiges' %>
    </div>
  </div>


  <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
  <%= link_to 'Abbrechen', document_url(@case, @folder, @document), class: 'btn btn-secondary mb-3' %>
<% end %>

<% end %>

app/views/documents/new_folder.html.erb
<%= render 'documents/template', note: nil, folder: @folder do %>

<h3 class="h3 mb-3 fw-bold">Ordner erstellen</h3>

<%= render 'documents/folder_form', folder: @folder, form_to: create_folder_url(@case) %>

<% end %>