config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "case#index"
  get "calendar", to: "calendar#global", as: :global_calendar
  get "timer", to: "time_recording#global", as: :global_timers

  scope "/profile" do
    get "edit", to: "profile#edit", as: :edit_profile
    post "edit", to: "profile#update", as: :update_profile

    get "writing-types", to: "profile#writing_types", as: :edit_writing_types

    get "writing-types/:writing_type_id", to: "profile#edit_writing_type", as: :edit_writing_type
    post "writing-types/:writing_type_id", to: "profile#update_writing_type", as: :update_writing_type
  end

  scope "/cases" do
    root to: "case#search", as: :cases
    get "new", to: "case#new", as: :new_case
    put "new", to: "case#create", as: :create_case
  end

  scope "/c/:case_id" do
    root to: "case#show", as: :show_case
    get "edit", to: "case#edit", as: :edit_case
    post "edit", to: "case#update", as: :update_case

    post "canonize", to: "case#canonize", as: :canonize_case

    get "pin", to: "case#pin", as: :pin_case
    get "unpin", to: "case#unpin", as: :unpin_case

    scope "/permissions" do
      root to: "permissions#index", as: :permissions

      get "new", to: "permissions#new", as: :new_permission
      post "new", to: "permissions#create", as: :create_permission

      get ":permission_id/edit", to: "permissions#edit", as: :edit_permission
      post ":permission_id/edit", to: "permissions#update", as: :update_permission

      get ":permission_id/delete", to: "permissions#delete", as: :delete_permission
      post ":permission_id/delete", to: "permissions#destroy", as: :destroy_permission
    end

    scope "/participants" do
      root to: "participants#index", as: :participants
      get "new", to: "participants#new", as: :new_participant
      post "new", to: "participants#create", as: :create_participant
      get ":participant_id/edit", to: "participants#edit", as: :edit_participant
      post ":participant_id/edit", to: "participants#update", as: :update_participant
      get ":participant_id/delete", to: "participants#delete", as: :delete_participant
      post ":participant_id/delete", to: "participants#destroy", as: :destroy_participant
    end

    scope "/represent" do
      get "new", to: "representments#new", as: :new_representment
      post "new", to: "representments#create", as: :create_representment
      get "new/:days/days", to: "representments#create_for_days", as: :create_representment_for_days
      get "clear", to: "representments#clear", as: :clear_representment
      get "step", to: "representments#step", as: :step
      get "clear-and-step", to: "representments#clear_and_step", as: :clear_and_step
    end

    scope "/notes" do
      root to: "notes#index", as: :notes
      get "new", to: "notes#new", as: :new_note
      post "new", to: "notes#create", as: :create_note
      get ":note_id/edit", to: "notes#edit", as: :edit_note
      post ":note_id/edit", to: "notes#update", as: :update_note
      get ":note_id/delete", to: "notes#delete", as: :delete_note
      post ":note_id/delete", to: "notes#destroy", as: :destroy_note
    end

    scope "/calendar" do
      root to: "calendar#index", as: :calendar
      get "new", to: "calendar#new", as: :new_event
      post "new", to: "calendar#create", as: :create_event
      get ":event_id/edit", to: "calendar#edit", as: :edit_event
      post ":event_id/edit", to: "calendar#update", as: :update_event
      get ":event_id/delete", to: "calendar#delete", as: :delete_event
      post ":event_id/delete", to: "calendar#destroy", as: :destroy_event
    end

    scope "/documents" do
      root to: "documents#index", as: :documents

      get "fo-:folder_id", to: "documents#folder", as: :folder
      get "fo/new", to: "documents#new_folder", as: :new_folder
      post "fo/new", to: "documents#create_folder", as: :create_folder
      get "fo-:folder_id/edit", to: "documents#edit_folder", as: :edit_folder
      post "fo-:folder_id/edit", to: "documents#update_folder", as: :update_folder

      get "fo-:folder_id/do-:document_id", to: "documents#document", as: :document
      get "fo-:folder_id/do/new", to: "documents#new_document", as: :new_document
      post "fo-:folder_id/do/new", to: "documents#create_document", as: :create_document
      get "fo-:folder_id/do-:document_id/edit", to: "documents#edit_document", as: :edit_document
      post "fo-:folder_id/do-:document_id/edit", to: "documents#update_document", as: :update_document

      get "fo-:folder_id/do-:document_id/i/new", to: "documents#new_document_item", as: :new_document_item
      post "fo-:folder_id/do-:document_id/i/new", to: "documents#create_document_item", as: :create_document_item
    end

    scope "/tasks" do
      root to: "tasks#index", as: :tasks

      get ":task_id/edit", to: "tasks#edit", as: :edit_task
      post ":task_id/edit", to: "tasks#update", as: :update_task
      get "new", to: "tasks#new", as: :new_task
      post "new", to: "tasks#create", as: :create_task
      get ":task_id/delete", to: "tasks#delete", as: :delete_task
      post ":task_id/delete", to: "tasks#destroy", as: :destroy_task

      get "column/:task_column_id/edit", to: "tasks#edit_task_column", as: :edit_task_column
      post "column/:task_column_id/edit", to: "tasks#update_task_column", as: :update_task_column
      get "column/new", to: "tasks#new_task_column", as: :new_task_column
      post "column/new", to: "tasks#create_task_column", as: :create_task_column
    end

    scope "/writing" do
      root to: "writing#index", as: :writings
      get ":type_id/new", to: "writing#new", as: :new_writing
      post ":type_id/new", to: "writing#create", as: :create_writing

      get "draft/:draft_id/edit", to: "writing#edit", as: :edit_writing
      post "draft/:draft_id/edit", to: "writing#update", as: :update_writing

      get "draft/:draft_id/finalize", to: "writing#finalize", as: :finalize_writing
      get "draft/:draft_id/download", to: "writing#download", as: :download_writing
    end

    scope "/timer" do
      root to: "time_recording#index", as: :timers

      get "start", to: "time_recording#start", as: :start_timer
      get "stop", to: "time_recording#stop", as: :stop_timer

      get "new", to: "time_recording#new", as: :new_timer
      post "new", to: "time_recording#create", as: :create_timer

      get ":time_record_id/edit", to: "time_recording#edit", as: :edit_timer
      post ":time_record_id/edit", to: "time_recording#update", as: :update_timer

      get ":time_record_id/delete", to: "time_recording#delete", as: :delete_timer
      post ":time_record_id/delete", to: "time_recording#destroy", as: :destroy_timer
    end
  end
end

app/controllers/time_recording_controller.rb
class TimeRecordingController < ApplicationController
  before_action :get_case, only: [ :start, :stop, :new, :create, :edit, :update, :delete, :destroy, :index ]
  before_action :get_time_record, only: [ :edit, :update, :delete, :destroy ]

  def global; end

  def index
    return if require_permission! :time_record_access
    render layout: "layouts/case_view"
  end

  def start
    return if require_permission! :time_record_access

    if TimeRecord.has_current_for_user? current_user
      flash[:danger] = "Du erfasst gerade eine andere Zeit. Du musst die andere Zeit stoppen, " \
                       "bevor du für diesen Vorgang die Zeit starten kannst."
      return redirect_to safe_path(params[:redirect_url])
    end

    TimeRecord.create!(
      case: @case,
      user: current_user,
      begins_at: DateTime.now,
      running: true,
      comment: nil
    )

    redirect_to safe_path(params[:redirect_url])
  end

  def stop
    return if require_permission! :time_record_access

    unless TimeRecord.has_current_for_case_and_user? @case, current_user
      flash[:danger] = "Deine Zeiterfassung läuft gerade gar nicht und kann daher auch nicht gestoppt werden."
      return redirect_to safe_path(params[:redirect_url])
    end

    time_record = TimeRecord.current_for_case_and_user @case, current_user
    time_record.stop!

    redirect_to safe_path(params[:redirect_url])
  end

  def new
    return if require_permission! :time_record_access
    @time_record = TimeRecord.new(
      case: @case, user: current_user,
      begins_at: DateTime.now
    )
    render layout: "layouts/case_view"
  end

  def create
    return if require_permission! :time_record_access
    begins_at = params[:time_record][:begins_at].in_time_zone(Rails.configuration.time_zone)
    ends_at = params[:time_record][:ends_at].in_time_zone(Rails.configuration.time_zone)
    of_user = User.find(params[:time_record][:user])

    if begins_at > ends_at
      ends_at = begins_et
    end

    TimeRecord.create!(
      case: @case,
      user: of_user,
      begins_at: begins_at,
      ends_at: ends_at,
      running: false,
      comment: params[:time_record][:comment]
    )

    flash[:success] = "Zeiteintragung wurde erfolgreich hinzugefügt"

    redirect_to timers_url(@case)
  end

  def edit
    return if require_permission! :time_record_access
    render layout: "layouts/case_view"
  end

  def update
    return if require_permission! :time_record_access
    begins_at = params[:time_record][:begins_at].in_time_zone(Rails.configuration.time_zone)
    ends_at = params[:time_record][:ends_at].in_time_zone(Rails.configuration.time_zone)

    if begins_at > ends_at
      ends_at = begins_et
    end

    @time_record.update!(
      comment: params[:time_record][:comment],
      begins_at: begins_at,
      ends_at: ends_at
    )

    flash[:success] = "Zeiteintragung wurde erfolgreich angepasst"

    redirect_to timers_url(@case)
  end

  def delete
    return if require_permission! :time_record_access
    render layout: "layouts/case_view"
  end

  def destroy
    return if require_permission! :time_record_access
    @time_record.destroy!()
    flash[:success] = "Zeiteintragung wurde erfolgreich gelöscht"
    redirect_to timers_url(@case)
  end

  protected

  def get_time_record
    @time_record = @case.time_records.where(user: current_user).find(params[:time_record_id])
  end
end

app/helpers/time_recording_helper.rb
module TimeRecordingHelper
end

app/views/time_recording/_form.html.erb
<%= form_with url: form_to, model: time_record, method: :post do |form| %>

  <div class="form-floating <%= time_record.persisted? ? 'mb-0' : 'mb-3' %>">
    <%= form.select :user, User.all.map { |u| [u.display_name, u.id]}, {selected: time_record.user&.id, include_blank: 'Ggf. auswählen...'}, { class: 'form-select', disabled: time_record.persisted? } %>
    <%= form.label :user, 'Nutzer/in' %>
  </div>

  <% unless time_record.new_record? %>
    <div class="form-floating">
      <%= form.text_field :duration_in_min, class: 'form-select', disabled: true, value: "#{min_to_fqtf time_record.duration_in_min}" %>
      <%= form.label :user, 'Dauer' %>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.datetime_field :begins_at, class: 'form-control', placeholder: '', step: 1 %>
    <%= form.label :begins_at, 'Beginn der erfassten Zeit' %>
  </div>

  <div class="form-floating mb-3">
    <%= form.datetime_field :ends_at, class: 'form-control', placeholder: '', step: 1 %>
    <%= form.label :ends_at, 'Ende der erfassten Zeit' %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :comment, class: 'form-control', placeholder: '' %>
    <%= form.label :comment, 'Kommentar' %>
  </div>

  <%= form.submit 'Speichern', class: 'btn btn-primary mb-3' %>
  <% unless time_record.new_record? %>
    <%= link_to 'Erfasste Zeit löschen', delete_timer_url(@case, time_record), class: 'btn btn-outline-danger mb-3' %>
  <% end %>
  <%= link_to 'Abbrechen', show_case_url(@case), class: 'btn btn-secondary mb-3' %>

<% end %>

app/views/time_recording/delete.html.erb
<%= render 'case/case_header', view: :permissions %>

<h2 class="h3 mb-3 fw-bold">Erfasste Zeit löschen</h2>

<p>Wollen Sie die folgende erfasste Zeit wirklich löschen?</p>
<p class="fw-bold"><%= @time_record.begins_at.strftime("%d.%m.%Y %H:%M") %> bis <%= @time_record.ends_at.strftime("%H:%M") %> (<%= min_to_fqtf @time_record.duration_in_min %>)<% if @time_record.comment %> &ndash; <%= @time_record.comment %><% end %></p>

<%= form_with url: destroy_timer_url(@case, @time_record), model: @time_record, method: :post do |form| %>
<%= form.submit 'Erfasste Zeit jetzt löschen', class: 'btn btn-danger mb-3' %>
<%= link_to 'Abbrechen', permissions_url(@case), class: 'btn btn-secondary mb-3' %>
<% end %>

app/views/time_recording/edit.html.erb
<%= render 'case/case_header', view: :time_recording %>

<h3 class="h3 mb-3 fw-bold">Erfasste Zeit bearbeiten</h3>

<%= render 'time_recording/form', time_record: @time_record, form_to: update_timer_url(@case, @time_record) %>

app/views/time_recording/global.html.erb
<h1 class="fw-bold mb-3">Deine erfassten Zeiten</h1>

<% TimeRecord.where(user: current_user, running: false).all \
    .group_by { |tr| tr.begins_at.to_date }.to_a \
    .sort_by { |k,v| k }.reverse.each do |k, v| %>
  <% total_time = v.map { |tr| tr.duration_in_min }.sum %>
  <h2 class="h4 mt-4 mb-3 fw-bold"><%= l(k, format: "%A, den %d.%m.%Y") %> &ndash; insgesamt: <%= min_to_fqtf total_time %></h2>

  <table class="table">
    <thead>
      <tr>
        <th colspan="2">Vorgang</th>
        <th>Kommentar</th>
        <th>Beginn</th>
        <th>Ende</th>
        <th>Dauer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% v.sort_by { |tr| tr.begins_at }.reverse.each do |tr| %>
        <tr>
          <td><%= link_to tr.case.case_no, show_case_url(tr.case), class: 'link-dark text-decoration-none' %></td>
          <td><%= link_to tr.case.title, show_case_url(tr.case), class: 'link-dark text-decoration-none' %></td>
          <td><%= tr.comment %></td>
          <td><%= tr.begins_at.strftime("%H:%M") %></td>
          <td><%= tr.ends_at.strftime("%H:%M") %></td>
          <td><%= min_to_fqtf tr.duration_in_min %></td>
          <td>
            <a href="<%= edit_timer_url(tr.case, tr) %>"
               class="btn btn-outline-secondary py-0 px-1 btn-sm">Bearbeiten</a>
            <a href="<%= delete_timer_url(tr.case, tr) %>"
               class="btn btn-outline-danger py-0 px-1 btn-sm">Löschen</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/time_recording/index.html.erb
<%= render 'case/case_header', view: :time_recording %>

<h1 class="h3 fw-bold mb-3">Erfasste Zeiten</h1>

<h2 class="h4 mt-4 mb-3 fw-bold">Überblick</h2>

<table class="table mb-1 mw-500px">
  <thead>
    <tr>
      <th>Benutzer</th>
      <th class="text-end">Erfasste Zeit</th>
      <th class="text-end">Betrag</th>
    </tr>
  </thead>
  <tbody>
    <% tsm_sum = 0 %>
    <% tbf_sum = 0 %>
    <% TimeRecord.where(case: @case, running: false).all \
        .group_by { |tr| tr.user.id }.to_a.map { |k, v| [k, v.map { |tr| tr.duration_in_min }.sum] } \
        .sort_by { |uid, tsm| tsm }.reverse.each do |uid, tsm| %>
    <tr>
      <td><%= User.find(uid).display_name %></td>
      <td class="font-monospace text-end"><%= min_to_fqtf tsm %></td>
      <% time_billing_factor = User.find(uid).time_billing_factor_in_ct %>
      <% unless time_billing_factor.blank? %>
        <td class="font-monospace text-end"><%= ("%.2f" % ((tsm / 60.0) * (time_billing_factor / 100.0))).sub(".", ",") %> EUR</td>
        <% tbf_sum += (tsm / 60.0) * (time_billing_factor / 100.0) %>
      <% end %>
    </tr>
    <% tsm_sum += tsm %>
    <% end %>
  </tbody>
  <% if tsm_sum != 0 %>
  <tfoot>
    <td class="fw-bold">insgesamt:</td>
    <td class="font-monospace text-end"><%= min_to_fqtf tsm_sum %></td>
    <td class="font-monospace text-end"><%= ("%.2f" % tbf_sum).sub(".", ",") %> EUR</td>
  </tfoot>
  <% end %>
</table>

<% TimeRecord.where(case: @case, running: false).all \
    .group_by { |tr| tr.begins_at.to_date }.to_a \
    .sort_by { |k,v| k }.reverse.each do |k, v| %>
  <% total_time = v.map { |tr| tr.duration_in_min }.sum %>
  <h2 class="h4 mt-4 mb-3 fw-bold"><%= k.strftime("%d.%m.%Y") %> &ndash; insgesamt: <%= min_to_fqtf total_time %></h2>

  <table class="table">
    <thead>
      <tr>
        <th>Vorgang</th>
        <th>Benutzer</th>
        <th>Kommentar</th>
        <th>Beginn</th>
        <th>Ende</th>
        <th>Dauer</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% v.sort_by { |tr| tr.begins_at }.reverse.each do |tr| %>
        <tr>
          <td><%= link_to tr.case.case_no, show_case_url(tr.case), class: 'link-dark text-decoration-none' %></td>
          <td><%= tr.user.display_name %></td>
          <td><%= tr.comment %></td>
          <td><%= tr.begins_at.strftime("%H:%M") %></td>
          <td><%= tr.ends_at.strftime("%H:%M") %></td>
          <td><%= min_to_fqtf tr.duration_in_min %></td>
          <td>
            <a href="<%= edit_timer_url(tr.case, tr) %>"
               class="btn btn-outline-secondary py-0 px-1 btn-sm">Bearbeiten</a>
            <a href="<%= delete_timer_url(tr.case, tr) %>"
               class="btn btn-outline-danger py-0 px-1 btn-sm">Löschen</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/time_recording/new.html.erb
<%= render 'case/case_header', view: :time_recording %>

<h3 class="h3 mb-3 fw-bold">Erfasste Zeit hinzufügen</h3>

<%= render 'time_recording/form', time_record: @time_record, form_to: create_timer_url(@case) %>